services:
  sclab-agent:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    ports:
      - "7890:7890"
    volumes:
      - ./logs:/data/logs
      - ./cert:/data/cert
      - ./jwt:/data/jwt
    env_file:
      - ./.env
    environment:
      - JWT_PRIVATE_KEY_PATH=/data/jwt/jwtRS256.key
      - JWT_PUBLIC_KEY_PATH=/data/jwt/jwtRS256.key.pub
      - TLS_CERT=/data/cert/cert.pem
      - TLS_KEY=/data/cert/privkey.pem
    extra_hosts:
      - "host.docker.internal:host-gateway"